# Generated by Django 3.1.5 on 2021-01-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='logwork',
            name='logedTime',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
